### ISSUE TITLE
Server Address field isn't focused when Direct Connection menu is opened

### ISSUE THREAD

**Issue by Scarlaid** [PotassiumMC/thorium#1]
### Issue explanation

From the main menu click on Multiplayer, then Direct Connection. Server Address field won't be focused. If you press keys or shortcuts, nothing changes until you click on the field.
### Mojira issue link

https://bugs.mojang.com/browse/MC-233042

### Other

This issue has been unsolved, can confirm in the lastest version of Minecraft - 1.18.2 
##### Video for the issue: https://streamable.com/hvsafa

**Comment by NoahvdAa** [comment]
This fix is included in [version 1.1.0](https://github.com/PotassiumMC/thorium/releases/tag/1.1.0).
