### ISSUE TITLE
The Outer End does not generate (including end cities) [1.19]

### ISSUE THREAD

**Issue by GeradesoLukas** [PotassiumMC/thorium#13]
### Expected behavior

End terrain and end cities generating

### Observed/Actual behavior

Only the little floating islands generating

### Steps/models to reproduce

Go to the outer end using a gateway / locate end cities (Does not work)

**Comment by NoahvdAa** [comment]
Thanks for reporting this. This has been fixed in 14f94b5 and will be included in the next release, which will be out shortly.
