### ISSUE TITLE
outer End Islands either generate nothing or only small_end_islands

### ISSUE THREAD

**Issue by AllyJaxx** [PotassiumMC/thorium#15]
### Expected behavior

All the different end biomes to show up correctly

### Observed/Actual behavior

Either absolutely nothing or only small_end_islands generate

### Steps/models to reproduce

-Load up any seed (I was using 1464723240762185746)
-Go to the outer end islands

### Other

![2022-06-27_14 05 15](https://user-images.githubusercontent.com/64360185/176006973-008e9113-1280-46fe-a881-dd83599582db.png)

**Comment by NoahvdAa** [comment]
Are you on version 1.3.0? This should've been fixed in [1.3.1](https://github.com/PotassiumMC/thorium/releases/tag/1.3.1).

**Comment by AllyJaxx** [comment]
Had checked a while ago to see if there was a update and had forgot to report this, so didn't check again. Seems the new version fixes it, my bad.

**Comment by NoahvdAa** [comment]
Thanks for confirming!
