### ISSUE TITLE
MC-195732 and MC-212926 not present in config

### ISSUE THREAD

**Issue by teleheel** [PotassiumMC/thorium#16]
### Expected behavior

There should be config options for MC-195732 and MC-212926 in thorium.conf.

### Observed/Actual behavior

The respective options are missing

### Steps/models to reproduce

Download latest version of Thorium.
Run the game.
Check that the options for the mentioned bug fixes are not included in thorium.conf.

**Comment by NoahvdAa** [comment]
MC-195732 and MC-212926 are both fixed by the same fix as MC-86252. In a future update, this will be shown in a comment in the config file. The config update is tracked in #6.
