### ISSUE TITLE
1.1.0 Incompatibilities

### ISSUE THREAD

**Issue by Scarlaid** [PotassiumMC/thorium#2]
### Expected behavior

**Works fine just like [1.0.0](https://github.com/PotassiumMC/thorium/releases/tag/1.0.0)**

### Observed/Actual behavior

Incompatible with CEM - Custom Entity Models 
Removes the mod doesn't solve the crash, causing a loading loop at startup

Run the game with only Thorium installed did not crash

### Steps/models to reproduce

1. Put both Thorium 1.1.0 and cem-0.7.0 into the mod folder
2. Run the game

### Here are the videos + logs
> Latest Thorium
- Run the game: https://streamable.com/mymkqz
- Log: [2022-03-30-6.log](https://github.com/PotassiumMC/thorium/files/8380463/2022-03-30-6.log)
> Lastest Thorium but without CEM
- Run the game: https://streamable.com/yiqftj
- Log: [2022-03-30-7.log](https://github.com/PotassiumMC/thorium/files/8380466/2022-03-30-7.log)
> Older Thorium
- Run the game: https://streamable.com/y82crq
- Log: [latest.log](https://github.com/PotassiumMC/thorium/files/8380468/latest.log)
> Sodium + Thorium only
- Run the game: https://streamable.com/ospcrw
- Log: [latest.log](https://github.com/PotassiumMC/thorium/files/8380490/latest.log)
> Thorium only
- Run the game: https://streamable.com/bm1pfx
- Log: [latest.log](https://github.com/PotassiumMC/thorium/files/8380526/latest.log)

**Comment by NoahvdAa** [comment]
Thank you for the detailed report. The issue appears to have been caused by an incompatbility with sodium-extra's (with CEM worsening it). I've created a new release that should fix this issue: [1.1.1](https://github.com/PotassiumMC/thorium/releases/tag/1.1.1). Could you verify whether this fix works?

**Comment by Scarlaid** [comment]
> Thank you for the detailed report. The issue appears to have been caused by an incompatbility with sodium-extra's (with CEM worsening it). I've created a new release that should fix this issue: [1.1.1](https://github.com/PotassiumMC/thorium/releases/tag/1.1.1). Could you verify whether this fix works?

[1.1.1](https://github.com/PotassiumMC/thorium/releases/tag/1.1.1) worked, no more startup loop issue
Cheers for the quick fix.

**Comment by NoahvdAa** [comment]
Thanks for confirming :)
