### ISSUE TITLE
Minor incompatibility with the mod "Cobblemon"

### ISSUE THREAD

**Issue by Veraxiel** [PotassiumMC/thorium#23]
### Expected behavior

Our mod extends the duration of our entities' deaths to allow for faint animations, so they should despawn 3 seconds after death.

### Observed/Actual behavior

Our entities despawn almost as soon as they die.

### Steps/models to reproduce

Killing a Cobblemon entity with Thorium installed.

### Other

Hello, I'm the art director for a mod called Cobblemon. I'm here because your bugfix for MC-84873 breaks our entity faint animations. We've not encountered the bug reportedly caused by extending death times in the original issue, which our devs tell me might be because we handle the death of the entity manually in our code and we only use the death timer to give the client a cue. We'd like to resolve this mod incompatibility, which means Thorium might have to make an exclusion for Cobblemon's entities, or perhaps tell us how we can do that on our end. Thanks.

**Comment by NoahvdAa** [comment]
Mojang fixed [MC-84873](https://bugs.mojang.com/browse/MC-84873) in 1.19.3, so our fix was removed when updating (04414bc)
