### ISSUE TITLE
Animated texture interpolation ignores alpha channel during transition from/to transparent pixels

### ISSUE THREAD

**Issue by Scarlaid** [PotassiumMC/thorium#8]
### Issue explanation

**If an animated texture that uses texture interpolation ({"interpolate": true} in the .mcmeta file) contains transparent pixels, the following behaviors can be observed:**

- When fading TO transparent pixels, i.e. having a pixel that starts opaque and becomes transparent in the next frame, during the interpolation they will fade to whatever the RGB values for the pixels are, ignoring the alpha channel (the game just behaves as if the pixel was fully opaque). Once the transition is over, those pixels instantly change from that color to transparent, which creates a very jarring effect.
- When fading FROM transparent pixels, i.e. having a pixel that starts transparent and becomes opaque in the next frame, they'll appear completely transparent until the transition is over. Once it is over, the correct color will, again, appear all of a sudden.

### Mojira issue link

https://bugs.mojang.com/browse/MC-144761

### Other

Said pretty much everything about ***a 2 line dif***
Still affects modern Minecraft versions till 1.18
![image](https://user-images.githubusercontent.com/90851437/166162009-b9929d97-65a0-42d4-af03-b9ed8ce639af.png)

I was surprised, tested myself as following the reproduction in the issue itself, and yes, this still isn't fixed in 1.18.2 
[This mod](https://www.curseforge.com/minecraft/mc-mods/mc-144761-fix) claimed to fix the issue, but it only works for 1.16.1 + crashed with Sodium/Continuity

**Comment by NoahvdAa** [comment]
This has been fixed in 6d6d368 and will be included in the next release :)

**Comment by Scarlaid** [comment]
any chance fixing #4 and #5 or you already did?
I'm just curious to ask

**Comment by NoahvdAa** [comment]
These haven't been fixed, I have not had time for them yet.
